apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/fabio-mrocha/kargo-advanced.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-advanced:{{path.basename}}
    spec:
      destination:
        namespace: guestbook-{{path.basename}}
        name: in-cluster
      project: guestbook
      source:
        path: ./
        repoURL: https://github.com/fabio-mrocha/kargo-advanced.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
